#####################################################
# Makefile: Makefile for Assignment5 EECS22 Fall2011
#
# 10/10/11 Weiwei Chen: initial solution version                  
#
#####################################################

# design names
DESIGN = MovieLab Test
MOVIES = out.yuv
CC = gcc
DEBUG = -g -DDEBUG 
#DEBUG = -O2
CFLAGS = -ansi -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)

all: MovieLab

#target to generate Image.o
Image.o: Image.h Image.c
	$(CC) $(CFLAGS) -c Image.c -o Image.o

#target to generate ImageList.o
ImageList.o: ImageList.h ImageList.c
	$(CC) $(CFLAGS) -c ImageList.c -o ImageList.o

#target to generate Movie.o
Movie.o: Movie.h Movie.c
	$(CC) $(CFLAGS) -c Movie.c -o Movie.o

#target to generate PhotoLab.o
MovieLab.o: MovieLab.c
	$(CC) $(CFLAGS) -c MovieLab.c -o MovieLab.o

#target to generate DIPs.o
DIPs.o: DIPs.h DIPs.c
	$(CC) $(CFLAGS) -c DIPs.c -o DIPs.o

MovieLab: MovieLab.o Image.o ImageList.o Movie.o DIPs.o
	$(CC) $(LFLAGS) MovieLab.o  Image.o ImageList.o Movie.o DIPs.o -o MovieLab


memcheck: MovieLab
	valgrind --leak-check=full MovieLab -i bird -o out -f 141 -s 352x288 -bw
	valgrind --leak-check=full MovieLab -i bird -o out -f 141 -s 352x288 -n
	valgrind --leak-check=full MovieLab -i bird -o out -f 141 -s 352x288 -hf
	valgrind --leak-check=full MovieLab -i bird -o out -f 141 -s 352x288 -vf
	valgrind --leak-check=full MovieLab -i bird -o out -f 141 -s 352x288 -rvs

play:
	~eecs22/bin/yay -s 352x288 -f 1 out.yuv
	
#target to clean the directory
clean:
	rm -f *.o *.jpg $(DESIGN) $(MOVIES)
    
